#组名
minecraft:
  #显示名称
  name: '&e原版禁用'
  #元数据 请勿修改
  base64: rO0ABXNyAENwZXJzLnR1ZXJzaGVuLmJhbml0ZW1saXN0LmNvbXBvdW5kbGlicmFyeS5ubXMuaW8uU2VyaWFsaXphYmxlRm9ybWF0YDaYA0w6e/0CAAJMAAJpZHQAEkxqYXZhL2xhbmcvU3RyaW5nO0wAC3RhZ0NvbXBvdW5kdAA/THBlcnMvdHVlcnNoZW4vYmFuaXRlbWxpc3QvY29tcG91bmRsaWJyYXJ5L25tcy9uYnQvVGFnQ29tcG91bmQ7eHB0AAlXT1JLQkVOQ0hzcgA9cGVycy50dWVyc2hlbi5iYW5pdGVtbGlzdC5jb21wb3VuZGxpYnJhcnkubm1zLm5idC5UYWdDb21wb3VuZGCgE2mplflQAgABTAADbWFwdAAPTGphdmEvdXRpbC9NYXA7eHIAOXBlcnMudHVlcnNoZW4uYmFuaXRlbWxpc3QuY29tcG91bmRsaWJyYXJ5Lm5tcy5uYnQuVGFnQmFzZQkkA28hsKYEAgAAeHBzcgARamF2YS51dGlsLkhhc2hNYXAFB9rBwxZg0QMAAkYACmxvYWRGYWN0b3JJAAl0aHJlc2hvbGR4cD9AAAAAAAAAdwgAAAAQAAAAAHg=
  #lore
  lore:
    - '&e点击查看 &b原版禁用 &e禁用列表'
  list:
    #节点名称
    名片:
      #元数据 请勿修改
      base64: rO0ABXNyAENwZXJzLnR1ZXJzaGVuLmJhbml0ZW1saXN0LmNvbXBvdW5kbGlicmFyeS5ubXMuaW8uU2VyaWFsaXphYmxlRm9ybWF0YDaYA0w6e/0CAAJMAAJpZHQAEkxqYXZhL2xhbmcvU3RyaW5nO0wAC3RhZ0NvbXBvdW5kdAA/THBlcnMvdHVlcnNoZW4vYmFuaXRlbWxpc3QvY29tcG91bmRsaWJyYXJ5L25tcy9uYnQvVGFnQ29tcG91bmQ7eHB0AAhOQU1FX1RBR3NyAD1wZXJzLnR1ZXJzaGVuLmJhbml0ZW1saXN0LmNvbXBvdW5kbGlicmFyeS5ubXMubmJ0LlRhZ0NvbXBvdW5kYKATaamV+VACAAFMAANtYXB0AA9MamF2YS91dGlsL01hcDt4cgA5cGVycy50dWVyc2hlbi5iYW5pdGVtbGlzdC5jb21wb3VuZGxpYnJhcnkubm1zLm5idC5UYWdCYXNlCSQDbyGwpgQCAAB4cHNyABFqYXZhLnV0aWwuSGFzaE1hcAUH2sHDFmDRAwACRgAKbG9hZEZhY3RvckkACXRocmVzaG9sZHhwP0AAAAAAAAB3CAAAABAAAAAAeA==
      #lore
      lore:
        - '§3禁止原因: §b改名'
    #节点名称
    TNT:
      #元数据 请勿修改
      base64: rO0ABXNyAENwZXJzLnR1ZXJzaGVuLmJhbml0ZW1saXN0LmNvbXBvdW5kbGlicmFyeS5ubXMuaW8uU2VyaWFsaXphYmxlRm9ybWF0YDaYA0w6e/0CAAJMAAJpZHQAEkxqYXZhL2xhbmcvU3RyaW5nO0wAC3RhZ0NvbXBvdW5kdAA/THBlcnMvdHVlcnNoZW4vYmFuaXRlbWxpc3QvY29tcG91bmRsaWJyYXJ5L25tcy9uYnQvVGFnQ29tcG91bmQ7eHB0AANUTlRzcgA9cGVycy50dWVyc2hlbi5iYW5pdGVtbGlzdC5jb21wb3VuZGxpYnJhcnkubm1zLm5idC5UYWdDb21wb3VuZGCgE2mplflQAgABTAADbWFwdAAPTGphdmEvdXRpbC9NYXA7eHIAOXBlcnMudHVlcnNoZW4uYmFuaXRlbWxpc3QuY29tcG91bmRsaWJyYXJ5Lm5tcy5uYnQuVGFnQmFzZQkkA28hsKYEAgAAeHBzcgARamF2YS51dGlsLkhhc2hNYXAFB9rBwxZg0QMAAkYACmxvYWRGYWN0b3JJAAl0aHJlc2hvbGR4cD9AAAAAAAAAdwgAAAAQAAAAAHg=
      lore:
        - '§3禁止原因: §b爆炸破坏'
    #节点名称
    鞍:
      #元数据 请勿修改
      base64: rO0ABXNyAENwZXJzLnR1ZXJzaGVuLmJhbml0ZW1saXN0LmNvbXBvdW5kbGlicmFyeS5ubXMuaW8uU2VyaWFsaXphYmxlRm9ybWF0YDaYA0w6e/0CAAJMAAJpZHQAEkxqYXZhL2xhbmcvU3RyaW5nO0wAC3RhZ0NvbXBvdW5kdAA/THBlcnMvdHVlcnNoZW4vYmFuaXRlbWxpc3QvY29tcG91bmRsaWJyYXJ5L25tcy9uYnQvVGFnQ29tcG91bmQ7eHB0AAZTQURETEVzcgA9cGVycy50dWVyc2hlbi5iYW5pdGVtbGlzdC5jb21wb3VuZGxpYnJhcnkubm1zLm5idC5UYWdDb21wb3VuZGCgE2mplflQAgABTAADbWFwdAAPTGphdmEvdXRpbC9NYXA7eHIAOXBlcnMudHVlcnNoZW4uYmFuaXRlbWxpc3QuY29tcG91bmRsaWJyYXJ5Lm5tcy5uYnQuVGFnQmFzZQkkA28hsKYEAgAAeHBzcgARamF2YS51dGlsLkhhc2hNYXAFB9rBwxZg0QMAAkYACmxvYWRGYWN0b3JJAAl0aHJlc2hvbGR4cD9AAAAAAAAAdwgAAAAQAAAAAHg=
      lore:
        - '§3禁止原因: §b有bug，具体不知'
    #节点名称
    红石比较器:
      #元数据 请勿修改
        base64: rO0ABXNyAENwZXJzLnR1ZXJzaGVuLmJhbml0ZW1saXN0LmNvbXBvdW5kbGlicmFyeS5ubXMuaW8uU2VyaWFsaXphYmxlRm9ybWF0YDaYA0w6e/0CAAJMAAJpZHQAEkxqYXZhL2xhbmcvU3RyaW5nO0wAC3RhZ0NvbXBvdW5kdAA/THBlcnMvdHVlcnNoZW4vYmFuaXRlbWxpc3QvY29tcG91bmRsaWJyYXJ5L25tcy9uYnQvVGFnQ29tcG91bmQ7eHB0ABNSRURTVE9ORV9DT01QQVJBVE9Sc3IAPXBlcnMudHVlcnNoZW4uYmFuaXRlbWxpc3QuY29tcG91bmRsaWJyYXJ5Lm5tcy5uYnQuVGFnQ29tcG91bmRgoBNpqZX5UAIAAUwAA21hcHQAD0xqYXZhL3V0aWwvTWFwO3hyADlwZXJzLnR1ZXJzaGVuLmJhbml0ZW1saXN0LmNvbXBvdW5kbGlicmFyeS5ubXMubmJ0LlRhZ0Jhc2UJJANvIbCmBAIAAHhwc3IAEWphdmEudXRpbC5IYXNoTWFwBQfawcMWYNEDAAJGAApsb2FkRmFjdG9ySQAJdGhyZXNob2xkeHA/QAAAAAAAAHcIAAAAEAAAAAB4
        lore:
          - '§3禁止原因: §b卡服'
    #节点名称
    粘性活塞:
      #元数据 请勿修改
        base64: rO0ABXNyAENwZXJzLnR1ZXJzaGVuLmJhbml0ZW1saXN0LmNvbXBvdW5kbGlicmFyeS5ubXMuaW8uU2VyaWFsaXphYmxlRm9ybWF0YDaYA0w6e/0CAAJMAAJpZHQAEkxqYXZhL2xhbmcvU3RyaW5nO0wAC3RhZ0NvbXBvdW5kdAA/THBlcnMvdHVlcnNoZW4vYmFuaXRlbWxpc3QvY29tcG91bmRsaWJyYXJ5L25tcy9uYnQvVGFnQ29tcG91bmQ7eHB0ABJQSVNUT05fU1RJQ0tZX0JBU0VzcgA9cGVycy50dWVyc2hlbi5iYW5pdGVtbGlzdC5jb21wb3VuZGxpYnJhcnkubm1zLm5idC5UYWdDb21wb3VuZGCgE2mplflQAgABTAADbWFwdAAPTGphdmEvdXRpbC9NYXA7eHIAOXBlcnMudHVlcnNoZW4uYmFuaXRlbWxpc3QuY29tcG91bmRsaWJyYXJ5Lm5tcy5uYnQuVGFnQmFzZQkkA28hsKYEAgAAeHBzcgARamF2YS51dGlsLkhhc2hNYXAFB9rBwxZg0QMAAkYACmxvYWRGYWN0b3JJAAl0aHJlc2hvbGR4cD9AAAAAAAAAdwgAAAAQAAAAAHg=
        lore:
          - '§3禁止原因: §b有bug，刷物品'


